### ISSUE TITLE
Review requested

### ISSUE THREAD

**Issue by evildmp** [divio/divio-cloud-docs#1]
* [x] What **architecture** material in https://github.com/divio/divio-cloud-docs/blob/master/background/divio-cloud-architecture.rst should remain here, and what should be moved to https://divio-ch.atlassian.net/wiki/display/TC/Divio+Cloud+-+general+description+and+policies+for+clients?

* [x] What **policy** material in https://github.com/divio/divio-cloud-docs/blob/master/background/divio-cloud-policies.rst should remain here, and what should be moved to https://divio-ch.atlassian.net/wiki/display/TC/Divio+Cloud+-+general+description+and+policies+for+clients

# Technical questions
* [x] Is there a way to configure a project locally to install addons? Or does this have to be initiated in the Control Panel?

# Policy/practice questions
* [x] Should the author and licence information of an addon package refer to the package itself, or to the package that it installs?

# To-do items
* [x] All to-do items are inline in the documentation and listed on the to-do page (documentation needs to be built to show the list).
